# Generated by Django 4.2.5 on 2023-10-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_last_name_profile_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                default="media/photo12.jpg", upload_to="media/profile_images"
            ),
        ),
    ]
