# Generated by Django 4.2.5 on 2023-10-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_profile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(default="photo12.jpg", upload_to="profile_images"),
        ),
    ]
